### ISSUE TITLE
Nomination Issue

### ISSUE THREAD

**Issue by TheBurnsby** [WebCab-Design/tnwf#1]
@AlexanderElias 
Here is an email I got from Angie at TNWF. Can you take a look at this asap?

> HI there, Got email from Connie and one of the prof at the U sent a nomination (3 times) and I didn’t get it.  I just did a test one and it didn’t come either.  After I did mine the cursor circled forever!!
thanks

**Comment by AlexanderElias** [comment]
@TheBurnsby this issue is fixed. It was a variable that was not checked before it's usage.
