### ISSUE TITLE
Presenter Form Issue

### ISSUE THREAD

**Issue by TheBurnsby** [WebCab-Design/tnwf#2]
@AlexanderElias Just got this from Angie. 

> The text boxes do not stop at 250 words – I’d rather they allow a few more than 250 but I clearly had about twice the limit and was not stopped
> When I clicked submit and selected the “will mail a check option” it gave me an error message pasted below.  I like how the word count countdown works on the fab 50 nomination – can that be added to the abstract submission too? 
>  
> If I select the “paypal” option the link works to get me to paypal but I don’t want to be changed the $90 so I wasn’t able to test if my abstract submission will work.  I have not received any abstracts yet and I was wanting to send out the submission information to our faculty before the break.

**Comment by AlexanderElias** [comment]
Added text box limit.

**Comment by AlexanderElias** [comment]
Added text box limit.
